<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * Repository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    /**
     * This method is used by Symfony's EntityUserProvider to map
     * the supplied 'username' to a user. We overwrite the method
     * to also allow supplying the email as 'username'.
     *
     * @param string $identifier
     * @return User|null
     */
    public function loadUserByUsername($identifier)
    {
        $qb = $this->createQueryBuilder('u');
        try {
            return $qb
                ->where($qb->expr()->eq('u.username', ':identifier'))
                ->orWhere($qb->expr()->eq('u.email', ':identifier'))
                ->setParameter('identifier', $identifier)
                ->getQuery()
                ->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        } catch (NonUniqueResultException $e) {
            // This should not happen.
            return null;
        }
    }
}
