imports:
    - { resource: config.yml }

parameters:
    elasticsearch_host: "%env(BONSAI_URL)%"

monolog:
    handlers:
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug

doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci