imports:
    - { resource: config_prod.yml }
    - { resource: config_heroku.php }

monolog:
    handlers:
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug