imports:
    - { resource: config_dev.yml }
    - { resource: config_dev_heroku.php }

monolog:
    handlers:
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug